### PR TITLE
Force SSL in production (and staging)

### PR DESCRIPTION
**Pull request by gabebw**
Now that Cloudflare gives us SSL, we should force people to use it instead of plain ol' HTTP.

### CODE REVIEW

**Comment by edwardloveall** [comment]
I dunno about this. You're introducing a lot of code here. Can you break it up into multiple commits?

**Comment by gabebw** [comment]
Good call. I broke it up into 1 line/commit -- is it easier to read now?

**Comment by edwardloveall** [comment]
Yes, much better. Thank you. :shipit:

**Comment by adarsh** [comment]
aw_snap

**Pull request merged**
