### PR TITLE
Update to Rails 5.2.2

### PR DESCRIPTION
**Pull request by gabebw**
The biggest change aside from Rails is probably moving `simple_form` from 3.5.0 to 4.0.0. However, we don't have any forms in our app, so it can't affect us.

@edwardloveall

### CODE REVIEW

**Comment by edwardloveall** [comment]
What do you think about removing simple form?

**Comment by gabebw** [comment]
I agree, let's remove `simple_form`. Please hold.

**Comment by gabebw** [comment]
@edwardloveall I opened a new PR to remove simple_form in #100

**Comment by gabebw** [comment]
simple_form has been removed, and I force-pushed this branch.

**Pull request merged**
